controller:
  service:
    internal:
      enabled: false
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp                       # type of connection, tcp / udp 
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-type:                                       # Type of loadbalancer 
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:355449129696:certificate/0f2e61e3-e6d7-4956-a96d-3bde45ab9a46   # Make sure to add your crt arn
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443