controller:
  service:
    internal:
      enabled: false
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp                       # type of connection, tcp / udp 
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-type:                                       # Type of loadbalancer 
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:398942634903:certificate/d471d44d-85a5-4ccb-9191-c3cd377167aa  # Make sure to add your crt arn
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443